set_property PACKAGE_PIN E3 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]

set_property PACKAGE_PIN N17 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports reset]

set_property PACKAGE_PIN D8 [get_ports {VGA_B[3]}]
set_property PACKAGE_PIN D7 [get_ports {VGA_B[2]}]
set_property PACKAGE_PIN C7 [get_ports {VGA_B[1]}]
set_property PACKAGE_PIN B7 [get_ports {VGA_B[0]}]
set_property PACKAGE_PIN A6 [get_ports {VGA_G[3]}]
set_property PACKAGE_PIN B6 [get_ports {VGA_G[2]}]
set_property PACKAGE_PIN A5 [get_ports {VGA_G[1]}]
set_property PACKAGE_PIN C6 [get_ports {VGA_G[0]}]
set_property PACKAGE_PIN A4 [get_ports {VGA_R[3]}]
set_property PACKAGE_PIN C5 [get_ports {VGA_R[2]}]
set_property PACKAGE_PIN B4 [get_ports {VGA_R[1]}]
set_property PACKAGE_PIN A3 [get_ports {VGA_R[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[0]}]

set_property PACKAGE_PIN B11 [get_ports hSync]
set_property PACKAGE_PIN B12 [get_ports vSync]
set_property IOSTANDARD LVCMOS33 [get_ports hSync]
set_property IOSTANDARD LVCMOS33 [get_ports vSync]

set_property PACKAGE_PIN F4 [get_ports ps2_clk]
set_property PACKAGE_PIN B2 [get_ports ps2_data]
set_property IOSTANDARD LVCMOS33 [get_ports ps2_clk]
set_property IOSTANDARD LVCMOS33 [get_ports ps2_data]

set_property PACKAGE_PIN P18 [get_ports move_down]
set_property PACKAGE_PIN P17 [get_ports move_left]
set_property PACKAGE_PIN M17 [get_ports move_right]
set_property PACKAGE_PIN M18 [get_ports move_up]
set_property IOSTANDARD LVCMOS33 [get_ports move_down]
set_property IOSTANDARD LVCMOS33 [get_ports move_left]
set_property IOSTANDARD LVCMOS33 [get_ports move_right]
set_property IOSTANDARD LVCMOS33 [get_ports move_up]

set_property IOSTANDARD LVCMOS33 [get_ports debug1]
set_property PACKAGE_PIN H17 [get_ports debug1]
set_property IOSTANDARD LVCMOS33 [get_ports debug2]
set_property PACKAGE_PIN K15 [get_ports debug2]
set_property IOSTANDARD LVCMOS33 [get_ports debug3]
set_property PACKAGE_PIN J13 [get_ports debug3]
set_property IOSTANDARD LVCMOS33 [get_ports debug4]
set_property PACKAGE_PIN N14 [get_ports debug4]

set_property PACKAGE_PIN T10 [get_ports {cathode[6]}]
set_property PACKAGE_PIN R10 [get_ports {cathode[5]}]
set_property PACKAGE_PIN K16 [get_ports {cathode[4]}]
set_property PACKAGE_PIN K13 [get_ports {cathode[3]}]
set_property PACKAGE_PIN P15 [get_ports {cathode[2]}]
set_property PACKAGE_PIN T11 [get_ports {cathode[1]}]
set_property PACKAGE_PIN L18 [get_ports {cathode[0]}]
set_property PACKAGE_PIN H15 [get_ports {cathode[7]}]
set_property PACKAGE_PIN J17 [get_ports {anode[0]}]
set_property PACKAGE_PIN J18 [get_ports {anode[1]}]
set_property PACKAGE_PIN T9 [get_ports {anode[2]}]
set_property PACKAGE_PIN J14 [get_ports {anode[3]}]
set_property PACKAGE_PIN P14 [get_ports {anode[4]}]
set_property PACKAGE_PIN T14 [get_ports {anode[5]}]
set_property PACKAGE_PIN K2 [get_ports {anode[6]}]
set_property PACKAGE_PIN U13 [get_ports {anode[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cathode[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cathode[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cathode[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cathode[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cathode[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cathode[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cathode[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cathode[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[7]}]

set_property PACKAGE_PIN E16 [get_ports {buttons[0]}]
set_property PACKAGE_PIN F13 [get_ports {buttons[1]}]
set_property PACKAGE_PIN G13 [get_ports {buttons[2]}]
set_property PACKAGE_PIN H16 [get_ports {buttons[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {buttons[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {buttons[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {buttons[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {buttons[3]}]

set_property PACKAGE_PIN D14 [get_ports {buttonsHigh[0]}]
set_property PACKAGE_PIN F16 [get_ports {buttonsHigh[1]}]
set_property PACKAGE_PIN G16 [get_ports {buttonsHigh[2]}]
set_property PACKAGE_PIN H14 [get_ports {buttonsHigh[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {buttonsHigh[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {buttonsHigh[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {buttonsHigh[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {buttonsHigh[3]}]

set_property PACKAGE_PIN C17 [get_ports strum]
set_property IOSTANDARD LVCMOS33 [get_ports strum]

set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets -of_objects [get_cells {proc/CPU/dx_ir_reg/loop1[27].dff/q_i_10__14}]]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets -of_objects [get_cells {proc/CPU/dx_ir_reg/loop1[3].dff/q_i_6__53}]]
